"""Make attendance unique by reg_id, date, and session_code_id

Revision ID: 4a153ec3f744
Revises: b076ffcdebdc
Create Date: 2025-07-06 18:58:18.656333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a153ec3f744'
down_revision = 'b076ffcdebdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index('uix_reg_id_date')
        batch_op.create_unique_constraint('uix_regid_date_session', ['reg_id', 'date', 'session_code_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint('uix_regid_date_session', type_='unique')
        batch_op.create_index('uix_reg_id_date', ['reg_id', 'date'], unique=True)

    # ### end Alembic commands ###
