"""Add PotentialClient table

Revision ID: 61479e1805d0
Revises: 4a153ec3f744
Create Date: 2025-07-09 21:01:02.957173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61479e1805d0'
down_revision = '4a153ec3f744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('potential_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('potential_clients')
    # ### end Alembic commands ###
