"""Rebuilding schema after full table wipe

Revision ID: a4a094510199
Revises: ad8b1a3655da
Create Date: 2025-07-06 00:25:15.131479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4a094510199'
down_revision = 'ad8b1a3655da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('regular_wage', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('occupation', sa.String(length=80), nullable=False))
        batch_op.drop_index('uix_name_date')
        batch_op.create_unique_constraint('uix_reg_id_date', ['reg_id', 'date'])
        batch_op.drop_column('division')
        batch_op.drop_column('name')
        batch_op.drop_column('branch')
        batch_op.drop_column('roll_no')

    with op.batch_alter_table('student_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('occupation', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('regular_wage', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('overtime_wage', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('regular_hours', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('maximum_overtime_hours', sa.Integer(), nullable=True))
        batch_op.drop_index('name')
        batch_op.drop_index('rollno')
        batch_op.drop_column('division')
        batch_op.drop_column('name')
        batch_op.drop_column('branch')
        batch_op.drop_column('rollno')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('student_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rollno', mysql.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('branch', mysql.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('division', mysql.VARCHAR(length=80), nullable=False))
        batch_op.create_index('rollno', ['rollno'], unique=True)
        batch_op.create_index('name', ['name'], unique=True)
        batch_op.drop_column('maximum_overtime_hours')
        batch_op.drop_column('regular_hours')
        batch_op.drop_column('overtime_wage')
        batch_op.drop_column('regular_wage')
        batch_op.drop_column('occupation')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roll_no', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('branch', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('division', mysql.VARCHAR(length=10), nullable=True))
        batch_op.drop_constraint('uix_reg_id_date', type_='unique')
        batch_op.create_index('uix_name_date', ['name', 'date'], unique=True)
        batch_op.drop_column('occupation')
        batch_op.drop_column('regular_wage')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
