"""Initial schema (no foreign keys)

Revision ID: ad8b1a3655da
Revises: 
Create Date: 2025-07-02 15:51:03.173497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8b1a3655da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.String(length=20), nullable=True),
    sa.Column('end_time', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('roll_no', sa.String(length=20), nullable=False),
    sa.Column('division', sa.String(length=10), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('reg_id', sa.String(length=100), nullable=True),
    sa.Column('session_code_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'date', name='uix_name_date')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('reg_id', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('session_code_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('attendance')
    # ### end Alembic commands ###
