"""Make regid unique per session_code_id

Revision ID: b076ffcdebdc
Revises: a4a094510199
Create Date: 2025-07-06 18:43:29.729005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b076ffcdebdc'
down_revision = 'a4a094510199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_data', schema=None) as batch_op:
        batch_op.drop_index('regid')
        batch_op.create_unique_constraint('uq_regid_per_session', ['regid', 'session_code_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_data', schema=None) as batch_op:
        batch_op.drop_constraint('uq_regid_per_session', type_='unique')
        batch_op.create_index('regid', ['regid'], unique=True)

    # ### end Alembic commands ###
