"""Add TimeEntry model for multi-session attendance tracking

Revision ID: c4bd612aafdb
Revises: 61479e1805d0
Create Date: 2025-07-21 10:14:16.670896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4bd612aafdb'
down_revision = '61479e1805d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reg_id', sa.String(length=100), nullable=False),
    sa.Column('session_code_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('entry_type', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('occupation', sa.String(length=80), nullable=False),
    sa.Column('regular_wage', sa.Float(), nullable=False),
    sa.CheckConstraint("entry_type IN ('check_in', 'check_out')", name='check_entry_type'),
    sa.CheckConstraint('sequence_number > 0', name='check_sequence_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.create_index('idx_employee_date', ['reg_id', 'session_code_id', 'date'], unique=False)
        batch_op.create_index('idx_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.drop_index('idx_timestamp')
        batch_op.drop_index('idx_employee_date')

    op.drop_table('time_entries')
    # ### end Alembic commands ###
