"""Initial migration

Revision ID: 485b4c1f870e
Revises: 
Create Date: 2025-06-24 15:07:13.428251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485b4c1f870e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.String(length=20), nullable=True),
    sa.Column('end_time', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('roll_no', sa.String(length=20), nullable=False),
    sa.Column('division', sa.String(length=10), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('reg_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('rollno', sa.String(length=120), nullable=False),
    sa.Column('division', sa.String(length=80), nullable=False),
    sa.Column('branch', sa.String(length=80), nullable=False),
    sa.Column('regid', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('regid'),
    sa.UniqueConstraint('rollno')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('reg_id', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('student_data')
    op.drop_table('attendance')
    # ### end Alembic commands ###
