"""Add unique constraint on name and date in Attendance

Revision ID: 5ecfeaf84b16
Revises: 485b4c1f870e
Create Date: 2025-06-24 16:48:25.458478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ecfeaf84b16'
down_revision = '485b4c1f870e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_name_date', ['name', 'date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint('uix_name_date', type_='unique')

    # ### end Alembic commands ###
