"""Add SessionCode model and foreign keys

Revision ID: d43f59e4ba48
Revises: 5ecfeaf84b16
Create Date: 2025-06-27 18:40:40.912904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd43f59e4ba48'
down_revision = '5ecfeaf84b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('business_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_code_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'session_code', ['session_code_id'], ['id'])

    with op.batch_alter_table('student_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_code_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'session_code', ['session_code_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_code_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'session_code', ['session_code_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('session_code_id')

    with op.batch_alter_table('student_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('session_code_id')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('session_code_id')

    op.drop_table('session_code')
    # ### end Alembic commands ###
